/**
Runnable examples functionality

Copyright: 2012 by Digital Mars

License:   http://boost.org/LICENSE_1_0.txt, Boost License 1.0

Authors:   Andrei Alexandrescu, Damian Ziemba
*/

/**
Script workflow:

1. Scan current document DOM tree for <pre> elements with class=d_code.
    <pre class="d_code">...</pre> blocks are generated by DDOC example sections.
2. Iterate each pre element and apply our custom form, replacing default <pre> block
3. Get text from original <pre> block, strip any spaces and newlines from it and compute md5sum
4. Look up mainPage map with md5sum as a key and see if there are any elements associated with this key
5. If yes: Add to our custom form default Standard input and/or Standard Arguments, stdin being 0 key, stdout 1 key.
6. If no: Just skip to point 7
7. Continue to next <pre> element and repeat begging from point 2 if there are still nodes left

How to add new example or update existing:

If example doesn't require any standard input neither standard argugments by default you are done.
Otherwise, copy example text without example separator ie:

------
[start here]
import std.stdio;

void main(string[] args) {
    writeln("Hello world. ", args);
    writeln("What's your name?");
    writeln("Hello ", readln());
}
[end here]
------

TL;DR
All examples are replaced with custom form by default. You need to do additional work only if you want
your example to have default standard input or default standard arguments.
*/

function safeVar(data, path)
{
    var p = path.split(".");
    var res = null;

    try
    {
        res = data[p[0]][p[1]];
        if (typeof res == "object")
            res = "";
    }
    catch (e)
    {
        return "";
    }

    return res;
}

// helpers
function childMatching(el, selector) {
    for (var i = 0; i < el.children.length; i++) {
        if (el.children[i].matches(selector)) return el.children[i];
    }
    return null;
}
function childrenMatching(el, selector) {
    var out = [];
    for (var i = 0; i < el.children.length; i++) {
        if (el.children[i].matches(selector)) out.push(el.children[i]);
    }
    return out;
}
function isVisible(el) {
    if (!el) return false;
    return getComputedStyle(el).display !== 'none' && el.offsetParent !== null;
}
function setText(el, t) { if (el) el.textContent = t; }
function emptyEl(el) { while (el && el.firstChild) el.removeChild(el.firstChild); }
function runReady(fn) {
    if (document.readyState !== 'loading') fn();
    else document.addEventListener('DOMContentLoaded', fn);
}

// compile the examples on the prerelease pages with dmd-nightly
var dmdCompilerBranch = location.href.indexOf("-prerelease/") >= 0 ? "dmd-nightly" : "dmd";

var backends = {
  dpaste: {
    url: "https://dpaste.dzfl.pl/request/",
    contentType: "application/x-www-form-urlencoded; charset=UTF-8",
    requestTransform: function(data) {
      // serialize as URL-encoded form
      var params = [];
      for (var k in data) {
        if (data.hasOwnProperty(k)) {
          params.push(encodeURIComponent(k) + "=" + encodeURIComponent(data[k]));
        }
      }
      return params.join("&");
    },
    parseOutput: function(data, opts) {
      var r = {};
      if (data.compilation === "undefined")
        return null;
      r.cout = safeVar(data, "compilation.stdout");
      r.stdout = safeVar(data, "runtime.stdout");
      r.stderr = safeVar(data, "runtime.stderr");
      r.ctime = parseInt(safeVar(data, "compilation.time"));
      r.rtime = parseInt(safeVar(data, "runtime.time"));
      r.cstatus = parseInt(safeVar(data, "compilation.status"));
      r.rstatus = parseInt(safeVar(data, "runtime.status"));
      r.cerr = safeVar(data, "compilation.err");
      r.rerr = safeVar(data, "runtime.err");
      r.defaultOutput = data.output || opts.defaultOutput;
      return r;
    }
  },
  tour: {
    url: "https://tour.dlang.org/api/v1/run",
    // send json as text/plain to avoid an additional preflight OPTIONS request
    // https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests
    contentType: "text/plain; charset=UTF-8",
    requestTransform: function(data) {
        var req = {
            source: data.code,
            // always execute unittests and main for backwards compatibility with examples
            args: "-unittest -main",
            runtimeArgs: "--DRT-testmode=run-main",
            compiler: dmdCompilerBranch
        }
        if (data.stdin) {
          req.stdin = data.stdin;
        }
        if (data.args) {
          req.args = data.args;
        }
        return JSON.stringify(req);
    },
    parseOutput: function(data, opts) {
      var r = {};
      if (data.success === "undefined") {
        return null;
      }
      var success = !(data.errors && data.errors.length > 0);
      r.cout = !success ? data.output : "";
      r.stdout = success ? data.output : "";
      r.stderr = !success ? data.output : "";
      r.ctime = "";
      r.rtime = "";
      r.cstatus = success ? 0 : 1;
      r.rstatus = 0; // not supported
      r.cerr = "";
      r.rerr = "";
      r.defaultOutput = data.output || opts.defaultOutput;
      return r;
    }
  }
};

function parseOutput(res, o, oTitle)
{
    if (!res)
    {
        setText(o, "Temporarily unavailable");
        return;
    }

    var output = "";

    if (res.cstatus != 0)
    {
        setText(oTitle, "Compilation output ("+res.cstatus+": "+res.cerr+")");
        setText(o, res.cout);
        return;
    }
    else
    {
        setText(oTitle, "Application output");
        if (res.cout != "")
            output = 'Compilation output: \n' + res.cout + "\n";

        output += (res.stdout == "" && res.stderr == "" ? res.defaultOutput : res.stdout);

        if (res.stderr != "")
            output += res.stderr;

        if (res.rstatus != 0)
            setText(oTitle, "Application output ("+res.rstatus+": "+res.rerr+")");
    }

    setText(o, output);
}

// wraps a unittest into a runnable script
function wrapIntoMain(code, compile) {
    // dynamically wrap into main if needed
    if (compile || code.indexOf("void main") >= 0 || code.indexOf("int main") >= 0) {
        return code;
    }
    else {
        var codeOut = "void main()\n{\n";
        codeOut += "    import std.stdio: write, writeln, writef, writefln;\n    ";
        codeOut += "#line 1\n";
        codeOut += code.split("\n").join("\n    ");
        codeOut += "\n}";
        return codeOut;
    }
}

runReady(function()
{
    setUpExamples();

    document.querySelectorAll('.runnable-examples').forEach(function(root) {
        var el = childMatching(root, 'pre');
        if (!el) return;

        var stdinNode = childMatching(root, '.runnable-examples-stdin');
        var argsNode = childMatching(root, '.runnable-examples-args');
        var stdin = stdinNode ? stdinNode.textContent : '';
        var args = argsNode ? argsNode.textContent : '';

        if (stdin.length > 0)
        {
            stdin = '<div class="d_code_stdin"><span class="d_code_title">Standard input</span><br>'
                  + '<textarea class="d_code_stdin">'+stdin+'</textarea></div>';
        }
        if (args.length > 0)
        {
            args = '<div class="d_code_args"><span class="d_code_title">Command line arguments</span><br>'
                + '<textarea class="d_code_args">'+args+'</textarea></div>';
        }

        var compile = el.parentNode.hasAttribute('data-compile');
        var runAttrs = 'value="' + (compile ? 'Compile' : 'Run') + '"';
        if (!compile)
            runAttrs += ' title="Note: Wraps code in `main` automatically if `main` is missing'
                + ' & imports std.stdio.write[f][ln]"';
        var orig = el.innerHTML;

        var html =
            '<div class="d_code"><pre class="d_code">'+orig+'</pre></div>'
            + '<div class="d_run_code">'
            + '<textarea class="d_code" style="display: none;"></textarea>'
            + stdin + args
            + '<div class="d_code_output"><span class="d_code_title">Application output</span><br><pre class="d_code_output" readonly>Running...</pre></div>'
            + '<input type="button" class="editButton" value="Edit">'
            + (args.length > 0 ? '<input type="button" class="argsButton" value="Args">' : '')
            + (stdin.length > 0 ? '<input type="button" class="inputButton" value="Input">' : '')
            + '<input type="button" class="runButton" ' + runAttrs + '>'
            + '<input type="button" class="resetButton" value="Reset">'
            + '<input type="button" class="openInEditorButton" value="Open in IDE"></div>';

        var tmp = document.createElement('div');
        tmp.innerHTML = html;
        var parent = el.parentNode;
        while (tmp.firstChild) {
            parent.insertBefore(tmp.firstChild, el);
        }
        parent.removeChild(el);
    });

    document.querySelectorAll('textarea.d_code').forEach(function(ta) {
        if (ta.className !== 'd_code') return; // jQuery's [class=d_code] = exact match
        var parent = ta.parentNode;
        var outputDiv = childMatching(parent, 'div.d_code_output');
        var hasStdin = childrenMatching(parent, '.inputButton').length > 0;
        var hasArgs  = childrenMatching(parent, '.argsButton').length > 0;
        var compile = parent.parentNode.hasAttribute('data-compile');
        setupTextarea(ta, {
          parent: parent,
          outputDiv: outputDiv,
          stdin: hasStdin,
          args: hasArgs,
          compile: compile,
          defaultOutput: "Succeed without output.",
          transformOutput: wrapIntoMain,
        });
    });
});

function setupTextarea(el, opts)
{
    opts = opts || {};
    opts = Object.assign({}, {
        stdin: false,
        args: false,
        transformOutput: function(out) { return out }
    }, opts);

    var backend = backends[opts.backend || "tour"];

    var parent = opts.parent;
    if (!parent) console.error("parent node node not found");
    var outputDiv = opts.outputDiv;
    if (!outputDiv) console.error("outputDiv node not found");

    parent.style.display = 'block';
    var orgSrc;
    {
        var siblingCodeDiv = childMatching(parent.parentNode, 'div.d_code');
        orgSrc = siblingCodeDiv ? childMatching(siblingCodeDiv, 'pre.d_code') : null;
    }

    var prepareForMain = function()
    {
        var src = orgSrc ? orgSrc.textContent : '';
        var arr = src.split("\n");
        var str = "";
        for (var i = 0; i < arr.length; i++)
        {
            str += arr[i]+"\n";
        }
        return str;
    };

    var editor;
    var code; // wrapper element produced by CodeMirror
    function initializeEditor(){
      if (typeof editor !== "undefined") return;
      editor = CodeMirror.fromTextArea(el, {
          lineNumbers: true,
          tabSize: 4,
          indentUnit: 4,
          indentWithTabs: true,
          mode: "text/x-d",
          lineWrapping: true,
          theme: "eclipse",
          readOnly: false,
          matchBrackets: true
      });
      editor.setValue(prepareForMain());
      code = editor.getWrapperElement();
      code.style.display = 'none';
    }

    var height = function(diff) {
        var par = code != null ? code : childMatching(parent.parentNode, 'div.d_code');
        if (!par) return '0px';
        return (parseInt(getComputedStyle(par).height) - diff) + 'px';
    };

    var runBtn = childMatching(parent, '.runButton');
    var editBtn = childMatching(parent, '.editButton');
    var resetBtn = childMatching(parent, '.resetButton');
    var openInEditorBtn = childMatching(parent, '.openInEditorButton');

    var plainSourceCode = childMatching(parent.parentNode, 'div.d_code');

    var output = childMatching(outputDiv, 'pre.d_code_output');
    var outputTitle = childMatching(outputDiv, 'span.d_code_title');
    var argsBtn, argsDiv, argsArea, orgArgs;
    var inputBtn, stdinDiv, stdinArea, orgStdin;
    if (opts.args) {
        argsBtn = childMatching(parent, 'input.argsButton');
        argsDiv = childMatching(parent, 'div.d_code_args');
        argsArea = argsDiv ? childMatching(argsDiv, 'textarea.d_code_args') : null;
        orgArgs = argsArea ? argsArea.value : '';
    }
    if (opts.stdin) {
        inputBtn = childMatching(parent, 'input.inputButton');
        stdinDiv = childMatching(parent, 'div.d_code_stdin');
        stdinArea = stdinDiv ? childMatching(stdinDiv, 'textarea.d_code_stdin') : null;
        orgStdin = stdinArea ? stdinArea.value : '';
    }

    var hideAllWindows = function(optArguments)
    {
        optArguments = optArguments || {};
        if (opts.stdin && stdinDiv) stdinDiv.style.display = 'none';
        if (opts.args && argsDiv) argsDiv.style.display = 'none';
        outputDiv.style.display = 'none';
        if (!optArguments.keepPlainSourceCode && plainSourceCode) {
            plainSourceCode.style.display = 'none';
        }
        if (!optArguments.keepCode && code) {
            code.style.display = 'none';
        }
    };

    if (opts.args && argsBtn) {
        argsBtn.addEventListener('click', function(){
            resetBtn.style.display = 'inline-block';
            if (argsArea) argsArea.style.height = height(31);
            hideAllWindows();
            argsDiv.style.display = 'block';
            if (argsArea) argsArea.focus();
        });
    }

    if (opts.stdin && inputBtn) {
        inputBtn.addEventListener('click', function(){
            resetBtn.style.display = 'inline-block';
            if (stdinArea) stdinArea.style.height = height(31);
            hideAllWindows();
            stdinDiv.style.display = 'block';
            if (stdinArea) stdinArea.focus();
        });
    }

    editBtn.addEventListener('click', function(){
        initializeEditor();
        resetBtn.style.display = 'inline-block';
        hideAllWindows();
        code.style.display = 'block';
        editor.refresh();
        editor.focus();
    });
    resetBtn.addEventListener('click', function(){
        resetBtn.style.display = 'none';
        editor.setValue(prepareForMain());
        if (opts.args && argsArea) argsArea.value = orgArgs;
        if (opts.stdin && stdinArea) stdinArea.value = orgStdin;
        hideAllWindows();
        if (plainSourceCode) plainSourceCode.style.display = 'block';
    });
    runBtn.addEventListener('click', function(){
        initializeEditor();
        resetBtn.style.display = 'inline-block';
        runBtn.disabled = true;
        var optArguments = {};
        if (opts.keepCode) {
            optArguments.keepCode = isVisible(code);
            optArguments.keepPlainSourceCode = isVisible(plainSourceCode);
        }
        hideAllWindows(optArguments);
        if (output) output.style.height = opts.outputHeight || height(31);
        outputDiv.style.display = 'block';
        setText(outputTitle, 'Application output');
        if (output) output.innerHTML = 'Running...';
        if (output) output.focus();

        var data = {
          code: opts.transformOutput(editor.getValue(), opts.compile)
        };
        if (opts.stdin && stdinArea) data.stdin = stdinArea.value;
        if (opts.args && argsArea) data.args = argsArea.value;

        fetch(backend.url, {
            method: 'POST',
            headers: { 'Content-Type': backend.contentType },
            body: backend.requestTransform(data)
        })
        .then(function(resp) {
            if (!resp.ok) throw new Error('HTTP ' + resp.status);
            return resp.json();
        })
        .then(function(data) {
            parseOutput(backend.parseOutput(data, opts), output, outputTitle);
            runBtn.disabled = false;
        })
        .catch(function(err) {
            if (output) output.innerHTML = 'Temporarily unavailable';
            if (typeof console != 'undefined') console.log(String(err));
            runBtn.disabled = false;
        });
    });
    openInEditorBtn.addEventListener('click', function(){
        var text = (editor && editor.getValue()) || prepareForMain();
        var url = "https://run.dlang.io?compiler=" + dmdCompilerBranch + "&args=-unittest&source=" + encodeURIComponent(opts.transformOutput(text));
        window.open(url, "_blank");
    });
    return editor;
}


function setUpExamples()
{
    /* Sets up expandable example boxes.
     * max-height and CSS transitions are used to animate the closing and opening for smooth animations even on less powerful devices
     */
    document.querySelectorAll('.example-box').forEach(function(box) {
        var boxId = box.id;
        var control = document.getElementById(boxId + '-control');
        if (!control) return;
        control.setAttribute('aria-controls', boxId);
        var showLabel = '<span>Show example <i class="fa fa-caret-down"></i></span>';
        var hideLabel = '<span>Hide example <i class="fa fa-caret-up"></i></span>';
        function toggle() {
            if (box.getAttribute('aria-hidden') === 'true') {
                box.setAttribute('aria-hidden', 'false');
                control.setAttribute('aria-expanded', 'true');
                control.innerHTML = hideLabel;
                box.style.maxHeight = box.scrollHeight + 'px';
            } else {
                box.setAttribute('aria-hidden', 'true');
                control.setAttribute('aria-expanded', 'false');
                control.innerHTML = showLabel;
                box.style.maxHeight = '0';
            }
            return false;
        }
        control.addEventListener('click', function(e) { toggle(); e.preventDefault(); });
        toggle();
    });
    // NB: href needed for browsers to include the controls in the (keyboard) tab order
    document.querySelectorAll('.example-control').forEach(function(c) {
        c.setAttribute('href', '#');
    });
}
